enum OperationType {
    ADDITION,
    DIVISION,
    EQUALITY,
    EXPONENTIATION,
    GREATER_THAN,
    GREATER_THAN_OR_EQUAL_TO,
    INEQUALITY,
    LESS_THAN,
    LESS_THAN_OR_EQUAL_TO,
    MODULUS,
    MULTIPLICATION,
    NEGATION,
    SUBTRACTION,
}

export {OperationType};
